apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: crazy-cookies
  labels:
    app.kubernetes.io/name: backend
    app.kubernetes.io/part-of: crazy-cookies
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
        app.kubernetes.io/name: backend
        app.kubernetes.io/part-of: crazy-cookies
    spec:
      initContainers:
        - name: wait-for-mysql
          image: busybox:1.36
          command:
            - sh
            - -c
            - |
              until nc -z mysql 3306; do
                echo "Esperando MySQL..."; sleep 3
              done
      containers:
        - name: backend
          image: node:18-alpine
          ports:
            - containerPort: 3000
              name: http
          envFrom:
            - configMapRef:
                name: backend-config
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: crazy-cookies-secrets
                  key: DATABASE_URL
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: crazy-cookies-secrets
                  key: JWT_SECRET
            - name: JWT_REFRESH_SECRET
              valueFrom:
                secretKeyRef:
                  name: crazy-cookies-secrets
                  key: JWT_REFRESH_SECRET
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          command: ["node", "-e", "require('http').createServer((req,res)=>{res.writeHead(200);res.end('OK')}).listen(3000)"]
