apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: crazy-cookies

resources:
- deployment.yaml
- service.yaml

images:
- name: ghcr.io/der-matt02/e-commerce-crazy-cookies-frontend
  newName: ghcr.io/der-matt02/e-commerce-crazy-cookies-frontend
  newTag: sha-1d56805
